-- Forma core schema. FTS5 provides the BM25 leg of hybrid retrieval (ADR-2).

CREATE TABLE documents (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  state TEXT,
  license_type TEXT,
  source_url TEXT,
  filing_date TEXT, -- ISO yyyy-mm-dd; drives linear time-decay at query time
  page_count INTEGER,
  pdf_key TEXT,     -- R2 object key
  form_schema TEXT, -- JSON FormSchema generated by Haiku at ingest
  docling_version TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE chunks (
  id TEXT PRIMARY KEY,
  document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  parent_id TEXT,   -- table_summary rows point at their full-table parent
  kind TEXT NOT NULL DEFAULT 'text' CHECK (kind IN ('text','table','table_summary')),
  content TEXT NOT NULL,
  page_number INTEGER,
  coordinates TEXT, -- JSON SourceRect[] (normalized top-left origin)
  state TEXT,
  license_type TEXT,
  filing_date TEXT,
  embedded INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_chunks_document ON chunks(document_id);
CREATE INDEX idx_chunks_parent ON chunks(parent_id);

-- Contentless-delete FTS index kept in sync by triggers. Parent table chunks
-- (kind='table') are indexed too: exact fee amounts / form codes in table
-- cells should be findable lexically even though only summaries are embedded.
CREATE VIRTUAL TABLE chunks_fts USING fts5(
  content,
  content='chunks',
  content_rowid='rowid',
  tokenize='porter unicode61'
);

CREATE TRIGGER chunks_fts_insert AFTER INSERT ON chunks BEGIN
  INSERT INTO chunks_fts(rowid, content) VALUES (new.rowid, new.content);
END;

CREATE TRIGGER chunks_fts_delete AFTER DELETE ON chunks BEGIN
  INSERT INTO chunks_fts(chunks_fts, rowid, content) VALUES ('delete', old.rowid, old.content);
END;

CREATE TRIGGER chunks_fts_update AFTER UPDATE OF content ON chunks BEGIN
  INSERT INTO chunks_fts(chunks_fts, rowid, content) VALUES ('delete', old.rowid, old.content);
  INSERT INTO chunks_fts(rowid, content) VALUES (new.rowid, new.content);
END;

-- Local-dev vector store used only when DEV_MOCK_AI=1 (Vectorize has no local
-- simulator). Harmless and empty in deployed environments.
CREATE TABLE dev_vectors (
  chunk_id TEXT PRIMARY KEY,
  document_id TEXT NOT NULL,
  vector TEXT NOT NULL -- JSON number[]
);
